name: sdk

on:
  workflow_dispatch:
jobs:
  configure_buildroot_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache 
        id: br-cache
        uses: actions/cache@v3
        with:
          path: 'buildroot'
          key: ${{ runner.os }}-${{ hashFiles('embedded-CI-externals/configs/modbus-gateway_defconfig') }}
      - name: set the buildroot config
        id: br-config
        uses: fmahiant/docker-buildroot-action@v8
        with:
          make_target: 'modbus-gateway_defconfig'
          buildroot_path: 'buildroot'
          buildroot_external_path: 'embedded-CI-externals'
      - name: build the sdk
        id: br-sdk
        uses: fmahiant/docker-buildroot-action@v7
        with:
          make_target: 'sdk'
          buildroot_path: 'buildroot'
          buildroot_external_path: 'embedded-CI-externals'
      - name: store the artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-sdk
          path: buildroot/output/images/*sdk-buildroot.tar.gz
