name: sdk

on:
  workflow_dispatch:
jobs:
  configure_buildroot_job:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - 
        name: Cache 
        id: br-cache
        uses: actions/cache@v3
        with:
          path: 'buildroot'
          key: ${{ runner.os }}-${{ hashFiles('embedded-CI-externals/configs/modbus-gateway_defconfig') }}
      - 
        name: set the buildroot config
        id: br-config
        uses: fmahiant/docker-buildroot-action@v11
        with:
          make_target: 'modbus-gateway_defconfig'
          buildroot_path: 'buildroot'
          buildroot_external_path: 'embedded-CI-externals'
      - 
        name: build the sdk
        id: br-sdk
        uses: fmahiant/docker-buildroot-action@v11
        with:
          make_target: 'sdk'
          buildroot_path: 'buildroot'
          buildroot_external_path: 'embedded-CI-externals'
      - 
        name: store the artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-sdk
          path: buildroot/output/images/*sdk-buildroot.tar.gz
      - 
        name: move to docker-sdk directory
        run: mv buildroot/output/images/*sdk-buildroot.tar.gz ../../../docker-sdk/
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -     
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
  
      -
        name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker-sdk
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/fmahiant/modbus-gateway-sdk:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
